# Generated by Django 4.2.7 on 2023-12-15 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 15, 21, 10, 55, 777076), verbose_name='Опубликована'),
        ),
    ]
